steps:
  - label: ":parcel::docker: Build Test container"
    concurrency: 1
    concurrency_group: "build_test_container"
    command: docker build -f Dockerfile.dev -t cololight-devimage .

  - wait

  - label: ":bulb::hass: Run Tests"
    command: pytest
    plugins:
      - docker#v3.5.0:
          image: "cololight-devimage"
          workdir: /workspaces/homeassistant_cololight

  - block: ":rocket: Release"
    branches: 'master'
    prompt: "Release details"
    fields:
      - text: "Release Version"
        key: "release-version"
      - text: "Release Notes"
        key: "release-notes"
        default: "# New Features\n# Fixes"

  - label: ":rocket::bulb:"
    branches: 'master'
    command: ./scripts/release.sh
